language: java
jdk: oraclejdk8
install: true
script: ./mvnw clean install
mvn install:install-file "-Dfile=cobra.jar" "-DgroupId=com.cobra" "-DartifactId=cobra" "-Dversion=0.98.4" "-Dpackaging=jar" "-DgeneratePom=true"
cache:
  directories:
  - $HOME/.m2
  script:
    - ./mvnw clean install
    - bash <(curl -s https://codecov.io/bash)
