language: java
jdk: oraclejdk8
install: true
script: ./mvnw clean  install
- git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD:master
cache:
  directories:
  - $HOME/.m2
  script:
    - ./mvnw clean install
    - bash <(curl -s https://codecov.io/bash)
